# These are supported funding model platforms

github: [ "oracle", "angular", "laravel", "symfony", "jaisocx" ]
custom: [ "https://wise.com/pay/r/viEhr7u79LbKJWs", "https://wise.com/pay/me/illiap407" ]
